---
# ELK Statistics Stack Main Tasks

- name: Include ELK Statistics installation tasks
  include_tasks: install_elkstack.yml
  tags: [elkstatistic, install]

- name: Include ELK Statistics database setup tasks
  include_tasks: setup_database.yml
  tags: [elkstatistic, database]

- name: Include ELK Statistics configuration tasks
  include_tasks: configure_elkstack.yml
  tags: [elkstatistic, config]

- name: Include ELK Statistics cron tasks
  include_tasks: setup_cron.yml
  tags: [elkstatistic, cron]
